### ISSUE TITLE
Make IAM roles least privilege

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#127]
## `AdministratorAccess`
- `components/backup.yaml:        - arn:aws:iam::aws:policy/AdministratorAccess`
- `components/control-tower.yaml:        - arn:aws:iam::aws:policy/AdministratorAccess # fixme: least privilege`
  -> https://docs.aws.amazon.com/controltower/latest/userguide/access-control-managing-permissions.html#additional-console-required-permissions
- `components/rootmail.yaml:        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess`
  -> That might be OK, other quickstart does it as well for CFN: https://github.com/aws-quickstart/quickstart-trek10-serverless-enterprise-cicd/blob/16b0d49b3805539a51ab87edffb24f2fce3df7e9/templates/cross-account.template.yaml#L88-L102

## `TODO`:
- `components/rootmail.yaml:              Action: # TODO: least privilege`
- `components/rootmail.yaml:              Action: # TODO: least privilege`
- `components/rootmail.yaml:                        Action: # TODO: least privilege`

probably also needed for #91

**Comment by yawn** [comment]
Descoped from 1.0 (likely not need for #91). Side notes: access advisor produces a lot more service coverage (especially for Canary / federation token roles) than is actually used. Only sensible option at this point is to use CloudTrail logs on temporary access tokens (for Canaries: log access key in CWL).
