### ISSUE TITLE
Root email handling

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#13]
Solution for secure handling of root emails.

- [x] Delegated hosted zone for root emails (master), potentially with reusable delegation sets
- [x] SES domain verification, DKIM/MX records and bucket routing (master)
- [x] Lambda for body parsing / shortening and creation of Ops Santa tickets
- [x] ~~Lambda and root scoped KMS DBP for S3~~ Descoped to #101
- [x] Delegation verification procedure & documentation
- [x] Trigger CT stack run after SES verification is complete
- [x] Enable happy path integration test
- [x] Enable EICAR integration test
- [x] Enable GTUBE path integration test
- [x] ~~Deeplinking to mails~~ Descobed until AWS supports deep links to S3 Objects
- [ ] Discovery of known classes of emails, using "initial root password recovery" (setting security question, password and OATH token)
- [x] ADR 

Workmail is out since it requires directories and cannot handle authentication with regular AWS principals.

**Comment by yawn** [comment]
Last things missing: opeex , KMS support (do we want/need this?)

**Comment by yawn** [comment]
Spiking integration tests like this: 

```
export AWS_PAGER=
export AWS_REGION=eu-west-1
export IDENTITY=aws.4f194a46-fe09-4233-9542-3dab6804f170.de

export SENDER="test@$IDENTITY"
export RECIPIENT="root+abcd@$IDENTITY"

aws ses send-email --destination "ToAddresses=$RECIPIENT" --from "$SENDER" --subject "This should pass" --text "This is a mail body"

aws ses send-email --destination "ToAddresses=$RECIPIENT" --from "$SENDER" --subject "This should be SPAM" --text "XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X"

TEMPFILE=$(mktemp)
trap "{ rm -f $TEMPFILE; }" EXIT

echo '{"Data": "From: '${SENDER}'\\nTo: '${RECIPIENT}'\\nSubject: 'This should be a VIRUS'\\nMIME-Version: 1.0\\nContent-type: Multipart/Mixed; boundary=\"NextPart\"\\n\\n--NextPart\\nContent-Type: text/plain\\n\\n'This is a mail body with a virus attachment'\\n\\n--NextPart\\nContent-Type: 'text/plain';\\nContent-Disposition: attachment;\\nContent-Transfer-Encoding: base64;\\n filename=\"'virus.txt'\"\\n\\n'WDVPIVAlQEFQWzRcUFpYNTQoUF4pN0NDKTd9JEVJQ0FSLVNUQU5EQVJELUFOVElWSVJVUy1URVNULUZJTEUhJEgrSCo='\\n--NextPart--"}' > $TEMPFILE

aws ses send-raw-email --cli-binary-format raw-in-base64-out --raw-message file://$TEMPFILE
```

It looks like as if SES does not support sending mails with virus payloads, not even fake ones. Sad!

**Comment by yawn** [comment]
I have no clue how to do an integration test for virus scanning. Sending mails with EICAR attachments via SES fails silently, using sendmail using e.g. 

```
TEMPFILE=$(mktemp)
trap "{ rm -f $TEMPFILE; }" EXIT

EMAIL_VIRUS=$(cat <<EOF
From: $SENDER
To: $RECIPIENT
Subject: This should be a VIRUS
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="27e311db-33e7-48ba-ba2d-0e3caf9ea4b4"

--27e311db-33e7-48ba-ba2d-0e3caf9ea4b4
Content-Type: text/plain; charset="US-ASCII"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

This is a mail body

--1beb3e62-b09b-498d-aa29-4c5db04e9ab3
Content-Type: application;
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="virus.com"

$(echo 'XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X' | base64)

--1beb3e62-b09b-498d-aa29-4c5db04e9ab3--
EOF
)

echo "$EMAIL_VIRUS" > $TEMPFILE

/usr/sbin/sendmail -t < $TEMPFILE
```

as well. Not really sure why there is a virus field in the SES event TBH ....

**Comment by s0enke** [comment]
Reopening since tests are not green: https://github.com/superwerker/superwerker/issues/105
