### ISSUE TITLE
Next-step for infrastructure

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#134]
This is a meta ticket for aligning on a future way of building the `sw` infrastructure. Topics are:

- faster development feedback cycles for individual functionality e.g. in Lambda functions ("local testing" and "better integration / unit tests")
- potentially enable external dependencies for Lambda functions
- more robustness against cloudformation failures (#116) to shield against the "everything works but one feature so we roll 99,9% of the superwerker installation back behaviour"

See also https://github.com/superwerker/superwerker/discussions/192

**Comment by yawn** [comment]
Related to #158 / more generally about development flow

**Comment by s0enke** [comment]
> faster development feedback cycles for individual functionality e.g. in Lambda functions ("local testing" and "better integration / unit tests")
> potentially enable external dependencies for Lambda functions

This would probably become possible by using SAM for packaging, a demo can be found in #189
