### ISSUE TITLE
Decouple release and dev/deployment/pipeline S3 buckets

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#137]
Currently, GitHub releases and the Deployment Pipeline use the same S3 Bucket `superwerker-deployment`. It might be a good idea to decouple this and create a dedicated S3 repo, e.g. `superwerker-releases` for the releases so that deployment/dev and releases cannot interfere and to ensure blast radius reduction.

## TODO

 - [x] Merge #251
 - [ ] Create a release to test the new workflow/bucket

**Comment by yawn** [comment]
Related to #158

**Comment by sbstjn** [comment]
- Deploy branches automatically to a `${branchname}/` prefix to S3 with GitHub Actions (`superwerker-deployment` bucket)
- Trigger CodePipeline for all merges on master
- After CodePipeline succeeded, trigger GitHub Action to create a new version
- Deploy version to a `${version}` prefix to S3 with GitHub Actions (manually, `superwerker-releases` bucket)
