### ISSUE TITLE
releases are created even if the test pipeline did not succeed

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#150]
Currently, pipeline run and release creation are not orchestrated. This means a release is created even if the pipeline run has not been successful. Should we change this?

**Comment by yawn** [comment]
Related to #158

**Comment by mavogel** [comment]
IMHO, a successful pipeline run is a prerequisite for a release.

**Comment by sbstjn** [comment]
We disabled the automatic releases yesterday, therefore this ticket is obsolete.
