### ISSUE TITLE
Cleanup and idempotency issues

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#155]
This is a list of resources that need cleanup:

1. S3 buckets (rootmail, control tower setup, canaries, config)
2. CWL Log Groups for all the embedded λ (either create explicitly or defer to CDK)
3. CW Dashboard (see also #208)
4. SES Domain Verification

Questionable:

1. sw created OpsItems

Not really a bug, more of a note for do-overs (potentially relevant as a note for brownfield installations). Currently only the backup component blocks do-overs through since `EnableCloudFormationStacksetsOrgAccessReadyWaitCondition` is never triggered by `CfnStackSetsReady` (since `EnableOrganizationsAccess` is not re-triggered). (see also #218)

Mitigation: just manually trigger the `CfnStackSetsReady` λ with any payload.

**Comment by s0enke** [comment]
This ticket seems to describe at least two different issues: Cleanup issues and convergent/brownfield issues. We might want to split it up to decouple the issues.
