### ISSUE TITLE
Pipeline failed during test: test_root_email_body_text (rootmail.RootMailTestCase)

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#157]
```
[Container] 2021/02/17 09:00:44 Running command AWS_REGION=${SUPERWERKER_REGION} AWS_DEFAULT_REGION=${SUPERWERKER_REGION} AWS_PROFILE=test_account ACCOUNT_FACTORY_ACCOUNT_ID=$(aws --profile test_account --region ${SUPERWERKER_REGION} cloudformation describe-stacks --stack-name superwerker-pipeline-account-factory-fixture --query "Stacks[0].Outputs[?OutputKey=='AccountId'].OutputValue" --output text) python3 -munittest rootmail.py backup.py tests.py
159 | ..F...................
160 | ======================================================================
161 | FAIL: test_root_email_body_text (rootmail.RootMailTestCase)
162 | ----------------------------------------------------------------------
163 | Traceback (most recent call last):
164 | File "/codebuild/output/src809257837/src/tests/rootmail.py", line 75, in test_root_email_body_text
165 | self.assertEqual(1, len(res['Entities']))
166 | AssertionError: 1 != 0
167 |  
168 | ----------------------------------------------------------------------
169 | Ran 22 tests in 742.453s
170 |  
171 | FAILED (failures=1)
172
```

Count: 3

Links:
 - https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/824014778649/projects/BuildAndTestProject-pV71zxUiaXub/build/BuildAndTestProject-pV71zxUiaXub%3Ac88ddc34-618c-4171-9ae7-4e59b0cf996f/?region=eu-west-1
 - https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/824014778649/projects/BuildAndTestProject-pV71zxUiaXub/build/BuildAndTestProject-pV71zxUiaXub%3A0ccc515d-a515-478a-9433-696b92ab0e91/?region=eu-west-1
 - https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/824014778649/projects/BuildAndTestProject-pV71zxUiaXub/build/BuildAndTestProject-pV71zxUiaXub%3A6241fbb8-91a1-4095-b3ad-8494360cd440/?region=eu-west-1

**Comment by s0enke** [comment]
> @yawn yawn added this to the Enhancements - 1.2 milestone 19 hours ago

I'd rather like to work on flaky tests / bugs / broken pipelines asap, not waiting for a particular milestone, otherwise, I'm afraid they get a [broken window](https://en.wikipedia.org/wiki/Broken_windows_theory) very soon. 
What do you think?

**Comment by yawn** [comment]
We didn't think that this is a real bug, more a timing issue in the pipeline. If it's more critical than that, let's move it to 1.1.

**Comment by s0enke** [comment]
Hopefully fixed by https://github.com/superwerker/superwerker/commit/1c8bf11c903a26d0e57b904c2f8291600fe208ff
