### ISSUE TITLE
Is auto-release a good idea?

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#158]
Currently, we auto-release at each commit to main. 

We also have adjusted it from the default:

```
on:
  push:
    branches: ['main']
```

This seems a bit "too much" for me. I'd like to control when to make a new release. E.g. collect a few bug fixes, then release. The auto semantic versioning can then still determine the correct version number. This would also might allow us to sync Milestone names and releases again (depending on the correct usage of feat/fix prefixes in commit messages). 

I checked a few other projects similar to superwerker and all of them also don't seem to have auto-release set on, so I think we should follow this good practice:

 - [AWS CDK](https://github.com/aws/aws-cdk)
 - [Org-formation](https://github.com/org-formation/org-formation-cli)
 - [ADF](https://github.com/awslabs/aws-deployment-framework)

Additional info:
 - [Intro article to semantic-release (has no auto-release as well)](https://kevinkreuzer.medium.com/the-way-to-fully-automated-releases-in-open-source-projects-44c015f38fd6).

**Comment by sbstjn** [comment]
[super-eks](https://github.com/superluminar-io/super-eks) uses a manual GitHub Action to trigger a new release. This works fine as well:

```yaml
on:
  workflow_dispatch: {}
```

https://github.com/superluminar-io/super-eks/blob/main/.github/workflows/release.yml

**Comment by s0enke** [comment]
thx @sbstjn - since you initially introduced the auto-release mechanism, I'd like to know your opinion on auto-release vs manual release as well. What do you think?

**Comment by sbstjn** [comment]
I guess, it depends on the purpose of a release/version.

- If you want to use a release/version as a tool for communication, we might switch to a manual trigger
- if you want to use a release/version as a point-in-time identifier, we can keep the automated workflow

With the current flow, a `major` release requires a "[BREAKING CHANGE](https://www.conventionalcommits.org/en/v1.0.0/)" commit message. Basically, `0.x.y` is handled automatically, `1.0.0` needs a special commit message and afterwards `1.x.y` is handled automatically again. I do not know if we care about manual triggers for `0.2.3` and/or `1.0.0` 🤷‍♀️ 🙈 

Shall we just flip a coin? :)

**Comment by s0enke** [comment]
Thanks for the feedback.

> I guess, it depends on the purpose of a release/version.

I want to be able to accumulate several changes / PRs into one release with one release number, as other projects do.  

> If you want to use a release/version as a tool for communication, we might switch to a manual trigger

Not only for communication but also for simplification for:
 - Announce on the mailing list / slack etc pp for every new release. 
 - Push changes upstream to Quickstart.
 
> if you want to use a release/version as a point-in-time identifier, we can keep the automated workflow

That's a commit-hash for me :) I am not yet ready for cattle releases :)

So I would propose to move to a manual trigger-based release workflow, e.g. with a GitHub action, and we still let the semantic-release determine the correct semantic version number.

**Comment by mavogel** [comment]
> So I would propose to move to a manual trigger-based release workflow, e.g. with a GitHub action, and we still let the semantic-release determine the correct semantic version number.

I favor this approach as well
