### ISSUE TITLE
Create live README / What Now? page as CW Dashboard

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#20]
CW Dashboard with Markdown and the following contents:

1. How to configure GSuite / Azure / Okta as SSO upstream (first example - others to follow) - use official AWS blogs as link targets
2. How to setup DNS delegation (using the "live" DNS entries there as well) for the setup to continue (to CT) - dummy domain as a feature for another version 
3. Whats in the package with deep links to the console (GD, SH / Audit account, Billing page, CT) - perhaps using relay state in permission sets?
4. Intro to ops 🎅 - later we'll delegate notifications to EventBridge clients for e.g. Slack or JIRA integrations
5. Update instructions (link to doc)
6. SOPs: a) create a workload b) create a new account

More ideas (probably new issue):
 - Sane AWS CLI setup with AWS SSO

# M1:
- [x] DNS delegation status and setup instructions #68 

# Ideas (descoped from M1)

## Setup state

- [ ] DNS delegation alarm as widget - clarify how we want to persist this info in `rootemail` (SSM parameters again?)
- [ ] Control Tower setup status (via SSM parameter)

## Next steps

- [x] How to delegate your domain to the `aws` subdomain using NS records
- [x] SSO post installation notes with links for GSuite / Azure (note *NOT* to link to the official SAML SSO doco from MS)
- [ ] Billing Setup: https://github.com/superwerker/superwerker/issues/28

## What now?

- [x] Info about SSO and documentation
- [x] Info about Guardduty and documentation
- [x] Deep links to OpsSanta and documentation

**Comment by s0enke** [comment]
descoped from 1.0

**Comment by chrisdag** [comment]
+1 on interest in seeing an Okta as an upstream SSO provider.  We also spend a lot of time teaching people how to set up the CLI for AWS SSO so having that sort of howto in the living docs would be interesting as well

**Comment by yawn** [comment]
Regarding the documentation - everything except Google (presumable because it lacks SCIM support) is documented [officially by AWS](https://docs.aws.amazon.com/singlesignon/latest/userguide/supported-idps.html) (so we only need to link to it).

For Google Workspaces we could fork https://github.com/awsdocs/aws-single-sign-on-user-guide and contribute to it. As of now the repo looks out of sync with the official rendering though.

**Comment by s0enke** [comment]
WIP proposal (cc @sbstjn @yawn )

```
          ## Next steps - finish setup

          - Setup AWS SSO
          - Setup AWS SSO with your identity provider (e.g. Office 365, Google Workspace, Okta)

          ## What now? Standard operating procedures

          - Create AWS accounts for each of your workloads via the [Control Tower Account Factory](/controltower/home/accountfactory/createAccount)
          - Check [OpsCenter for incoming events and messages](/systems-manager/opsitems/)
          - Check AWS Security Hub for security best practises
          - Check AWS Security Hub for threats

          ## Help and more information

          - superwerker open source project website
          - Architecture Decision records
          - Slack Channel
          - Mailing list
 ```

**Comment by sbstjn** [comment]
https://controltower.aws-management.tools/aa/sso/ has some detailed guides.

**Comment by sbstjn** [comment]
```
- Create AWS accounts for each of your workloads via the [Control Tower Account Factory](/controltower/home/accountfactory/createAccount)
- Check [OpsCenter for incoming events and messages](/systems-manager/opsitems/)
```

I like the service deep links. For basic topics, a deep link for experienced user is nice but we should always include a link to a more detailed "how to use" guide.

**Comment by sbstjn** [comment]
Based on the proposal by soenke, something like this?

<img width="782" alt="Screenshot 2021-03-11 at 13 08 16" src="https://user-images.githubusercontent.com/248965/110785146-e2e90b80-826a-11eb-850b-d2fb3b3e5372.png">

```markdown
## Next steps - finish setup

- Check [AWS Single Sign-On](/singlesignon) to manage users, groups, and account access
- Configure AWS SSO with identity providers:
  - [Azure AD](https://controltower.aws-management.tools/aa/sso/azure_ad/)
  - [Google Workspace](https://controltower.aws-management.tools/aa/sso/google/)
  - [Okta](https://controltower.aws-management.tools/aa/sso/okta/)
  - [OneLogin](https://controltower.aws-management.tools/aa/sso/onelogin/)

&nbsp;
## What now? Standard operating procedures

- Create AWS accounts for each of your workloads via the [Control Tower Account Factory](/controltower/home/accountfactory/createAccount)
- Check [OpsCenter for incoming events and messages](/systems-manager/opsitems/)
- Check [AWS Security Hub](/securityhub) for security best practises
- Check [Amazon GuardDuty](/guardduty) for threats

&nbsp;
## Help and more information
&nbsp;

- [superwerker on GitHub](https://github.com/superwerker/superwerker)
- [Architecture Decision Records](https://github.com/superwerker/superwerker/tree/main/docs/adrs)
- [AWS Quick Start deployment guide](https://aws-quickstart.github.io/quickstart-superwerker/)
- [#superwerker](https://og-aws.slack.com/archives/C01CQ34TC93) Slack channel in [og-aws](http://slackhatesthe.cloud)
- Mailing list
```

**Comment by yawn** [comment]
Looks lovely! For directly linking to the services I'd think we'd need to:

- Determine the correct accounts and available roles programmatically (this opens already a small can of worms since we somehow would need to rank best role candidates and pick the top spot / fallback to this information being unavailable for the current principal)
- Assume the picked role under the hood and construct a direct link to the services using `signin.aws.amazon.com/federation` (see e.g. `tests/console.py` or selected puppeteer scripts) OR
- Figure out how to dynamically constructs direct services link via the SSO portal (not sure that this is documented or can be reverse engineered though

**Comment by sbstjn** [comment]
Cross-account deep links. 🥺

![tenor (1)](https://user-images.githubusercontent.com/248965/110792757-12e8dc80-8274-11eb-9d0f-f777061d17d6.gif)

**Comment by s0enke** [comment]
Thanks, looks good, I have some remarks:

 - I would vote for scoping out cross-account deep links in this version to avoid a can of worms. Actually, IIRC only Security Hub and GuardDuty need deep links to the Audit Account. We coud also write something like "please login to the audit account and then click here".
 - I don't think we need to link to the QuickStart deployment guide since deployment is already done at this stage?!
 - We need to add regions to the links since the CW Dashboard is global but most of the links point to regional services, e.g. Account Factory, OpsCenter

**Comment by yawn** [comment]
Cross-account links will be impossible anyways I think w/o having the _actual_ principal in scope or at least available (e.g. by deploying the dashboard as OIDC application authenticating against the portal). Too complicated, not covering all bases (e.g. installation). Let's descope that.

**Comment by sbstjn** [comment]
Based on #139, we might also add an indicator for valid SNS subscription for important notifications that end up as OpsItems.

**Comment by kenhorn** [comment]
A vote for : SOPs: a) create a workload b) create a new account  -- as an item on its own. I have a sw CT set-up, but it's of no use if I can't deploy an app -- I'm new to CT/SSO and am getting lost in the docs/links.

**Comment by s0enke** [comment]
First iteration (except billing setup) PR: #185
