### ISSUE TITLE
RootMailReadyHandleWaitCondition timed out

### ISSUE THREAD

**Issue by cremich** [superwerker/superwerker#208]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### superwerker Version
0.12.2

### Expected Behaviour
RootMail stack created

### Actual Behaviour
RootMail stack creation timed out after I added the required NS records.

### Important Factoids
My domain is registered via route53 and I added the following NS entries in the hosted zone of my domain:
<img width="1792" alt="Screenshot 2021-04-23 at 11 36 25" src="https://user-images.githubusercontent.com/5345186/115852241-25843300-a428-11eb-82de-0742d92a6601.png">

What am I doing wrong? :D

### References

- #0000

**Comment by cremich** [comment]
It seems that the NS records differ. The first screenshots are the one that are in the SSM parameter and should be used to create the dashboard. The latter screenshot is the actual output in the dashboard. Which one are the right one?

<img width="659" alt="Screenshot 2021-04-23 at 21 23 48" src="https://user-images.githubusercontent.com/5345186/115920244-3493d100-a47a-11eb-9a39-5fbf881f2e2d.png">
<img width="405" alt="Screenshot 2021-04-23 at 21 24 10" src="https://user-images.githubusercontent.com/5345186/115920278-41182980-a47a-11eb-908b-cb22c26871a8.png">

**Comment by s0enke** [comment]
Hi,
the living documentation dashboard uses the same information (SSM parameter), so they should be the same. The only thing I can imagine is that the dashboard is outdated since it's generated dynamically. What does the "Updated at" timestamp shown in the dashboard?

**Comment by cremich** [comment]
That was the root cause. The first attempt of installing superwerker failed due to a different reason. And I looked to early in the dashboard. Resulting in copying outdated records. Idea for future improvement: also delete the dashboard if someone deletes the stack.

**Comment by s0enke** [comment]
Thanks for the improvement idea. Yes, the CW dashboard is created outside of CloudFormation which leads to orphans. It's tracked here: https://github.com/superwerker/superwerker/issues/155
