### ISSUE TITLE
Backup template deployment fails in EnableCloudFormationStacksetsOrgAccessReadyWaitCondition resource

### ISSUE THREAD

**Issue by dcd000** [superwerker/superwerker#218]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### superwerker Version
0.0.0-DEVELOPMENT
### Expected Behaviour

Backup template deployed successfully.
### Actual Behaviour

Backup template fails creating resource EnableCloudFormationStacksetsOrgAccessReadyWaitCondition.
I think that the condition is not met because canary function superwerker-cfn-org defined in EnableCloudFormationStacksetsOrgAccess resource fails with error:

```
ERROR: Step failed: stacksets URL: https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1 Error: 
Error: No node found for selector: #console-app > div > awsui-app-layout > div > main > div > div.awsui-app-layout__content--scrollable > div:nth-child(2) > span > div > awsui-alert > div > div.awsui-alert-body > div > div > span > div > div > div.col-s-3 > awsui-button > button
```

It seems there's no "awsui-alert" element in stackset page anymore.

**Comment by dcd000** [comment]
Please, also note that I am doing a redeploy so the organization already exists.

**Comment by s0enke** [comment]
Thanks, @dcd000 for the feedback! 
I added this one to the #155 collection (there was already a hint).

**Comment by davidem** [comment]
FYI: I've had the exact same issue 2 days ago when deploying Superwerker in an environment in eu-central-1, which already had a Control Tower deployment. It showed the same error in the syntheticsReport. I ended up disabling AWS Backup rollout. Funny thing: 2 days earlier in another account (also with Control Tower deployed, this time eu-west-1) I had no issues.

**Comment by antstanley** [comment]
Hi! I'm getting the same issue. No errors if I select no for backup. Fails if I select backup. I've run this a few times and it fails at the same point. The account is new, with no other resources in there, other than those created by Superwerker

Screenshot below of the issue

<img width="1023" alt="Screenshot 2021-08-23 at 12 47 17" src="https://user-images.githubusercontent.com/12698748/130442723-7c9e9d45-0fd6-4cd9-b6b9-5f8c1022f8e5.png">

**Comment by s0enke** [comment]
Yes, it's a common issue with superwerker being installed into existing environments. In this particular case it's the service managed CloudFormation already enabled, and superwerker does not check for it, since it's currently optimized for / tested with greenfield / fresh AWS accounts.

**Comment by antstanley** [comment]
Ahh... Is there a fix in the pipeline? Not urgent at all on my side, everything else is working and deployed. Will update and try again when a fix is available

**Comment by s0enke** [comment]
No short-term fix. A workaround is to [disable AWS Organizations access to CloudFormation managed stack](https://docs.aws.amazon.com/organizations/latest/userguide/services-that-can-integrate-cloudformation.html#integrate-disable-ta-cloudformation) sets before setting up superwerker so that superwerker can re-enable it. :)

I am working on a real solution where superwerker is more idempotent in case of existing installations (https://github.com/superwerker/superwerker/issues/116) but that will take some more time.
