### ISSUE TITLE
Make regions other than eu-west-1 work

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#23]
Regional requirements:

- CT & SSO support: https://github.com/superwerker/superwerker/issues/69
- SES receive support (this can be made a special case using stack set instances in a supported region though)

TODO:

 - [x] SES Receive handling through eu-west-1  #110 
 - [x] update rootmails ADR with new decisions
 - [x] Integration test for multi-region superwerker infrastructure

**Comment by yawn** [comment]
The following SES receive regions [are available](https://docs.aws.amazon.com/general/latest/gr/ses.html):

- us-east-1
- us-west-2
- eu-west-1

To simplify things, we'll map only the _sending_ infrastructure to eu-west-1 globally.

**Comment by s0enke** [comment]
Follow up bug fix for pipeline: https://github.com/superwerker/superwerker/commit/0fb1351b1591ca8671adcfc92712ade84b5cd361

**Comment by s0enke** [comment]
chore in 73a94b4
