### ISSUE TITLE
Unify builds to only use CodeBuild

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#239]
The superwerker infrastructure started with a [CodePipeline](tests/pipeline.yaml) which tests only the `main` branch. In https://github.com/superwerker/superwerker/issues/136 we added support for PR tests to get earlier feedback than pushing to `main`. The PR tests already use the same `buildspec.yaml` as the CodePipeline. To reduce confusion and to simplify the setup, we could now use the same infrastructure, which we use for testing PRs, also for the `main` branch - and in the end get rid of the CodePipeline.

## Technical hints

Sending notifications to Slack can probably be done with the [CodeBuild<>AWS Chatbot integration of CodeBuild](https://docs.aws.amazon.com/dtconsole/latest/userguide/welcome.html). Not sure if filtering for the `main` branch works (to keep the status quo which only notifies slack for CodePipeline/`main` runs).

### Must-have

 - [x] the CodeBuild job specified in `tests/build.yaml` is trigged on each commit to main
 - [ ] the daily build of superwerker `main` is still triggered (see trigger in `tests/pipeline.yaml`
 - [ ] notifications whether the latest build of `main` was successful are still being logged to the `#superwerker-notifications` channel (currently done by the CodePipeline and AWS Chatbot integration - probably clicked currently)
 - [ ] the CodePipeline and related resources defined in the CloudFormation stack `superwerker-tests-pipeline` are gone
 
 ### Should-have

 - [ ] Creating a new superwerker release should only be possible for a "green" build

**Comment by mavogel** [comment]
## Resources
- https://github.com/aws-samples/aws-codebuild-samples/blob/master/cloudformation/continuous-integration-nightly-checks.yml
- https://stackoverflow.com/questions/58034488/trigger-aws-cloudwatch-event-manually

**Comment by mavogel** [comment]
We fixed the branch name of the event, but no batch build is triggered. We move on from here in the next mobbing session

**Comment by mavogel** [comment]
We could not manage it with additional research today. @Reb-B will file a ticket at AWS if this is generally possible

**Comment by Reb-B** [comment]
> We could not manage it with additional research today. @Reb-B will file a ticket at AWS if this is generally possible

Ticket has been filed. Waiting on response.

**Comment by Reb-B** [comment]
> > We could not manage it with additional research today. @Reb-B will file a ticket at AWS if this is generally possible
> 
> Ticket has been filed. Waiting on response.

According to AWS support, triggering CodeBuild batch builds with an EventBridge event rule is not currently possible. They made a feature request in response to our query.
