### ISSUE TITLE
feat: billing setup

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#28]
Document or Automate if possible:

- [ ] VAT ID
- [ ] Tax inheritance
- [ ] Currency selection
- [ ] Send invoices as PDF + mailing list
- [ ] Enable cost management in member accounts - https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/control-access-billing.html#ControllingAccessWebsite-Activate?

**Comment by sbstjn** [comment]
The "Activate IAM Access" feature should be a default when using superwerker. Currently. the budget report can only be accessed using the root user account.

I started a discussion: https://github.com/superwerker/superwerker/discussions/216

**Comment by mavogel** [comment]
> The "Activate IAM Access" feature should be a default when using superwerker

Agree. This should be done (atm by hand until we solve #216 ) before deploying the superwerker stack

Note: we could use a baseline of this tool https://github.com/s0enke/aws-prober or even add it as a module
