### ISSUE TITLE
Only cover AWS accounts enrolled in Control Tower

### ISSUE THREAD

**Issue by sbstjn** [superwerker/superwerker#304]
For the backups feature, the CloudFormation stack [creates a new StackSet](https://github.com/superwerker/superwerker/blob/main/templates/backup.yaml#L114) which is deployed automatically to all AWS accounts [in the Root OU](https://github.com/superwerker/superwerker/blob/main/templates/backup.yaml#L133). This implementation will fail, if there are any "non-compatible" AWS accounts like suspended ones …

<img width="1040" alt="Screenshot 2022-05-31 at 14 11 44" src="https://user-images.githubusercontent.com/248965/171170344-2e020d7c-81ff-4601-9a70-80f0c1217c6e.png">

To fix this, we can delete the stack instance from the backup stack:

```bash
$ > aws cloudformation delete-stack-instances \
    --stack-set-name superwerker-backup \
    --deployment-targets Accounts=123456789001 \
    --regions eu-central-1 \
    --retain-stacks
```

Afterwards, the `superwerker-backup` stack(set) can be removed.

**Comment by s0enke** [comment]
Yes, superwerker is currently best installed into greenfield environments, as mentioned in the [FAQ](https://github.com/superwerker/superwerker#can-i-use-superwerker-for-existing-aws-set-ups. This issue would be one of many possible issues one could run into when rolling out superwerker into an existing AWS environment.

**Comment by sbstjn** [comment]
Duplicate of #291
