### ISSUE TITLE
CDK migration

### ISSUE THREAD

**Issue by bracki** [superwerker/superwerker#328]
# Problem

Currently superwerker is written in raw Cloudformation templates. While that's ok, it isn't exactly fun to work with. Especially if working with Lambda functions (which are currently inlined into the YAML templates), debugging and testing is a bit awkward.

# Possible solution

Migrate to AWS CDK 🎉 and all problems go away.

# Complication

Working with the CDK requires users to deploy templates using the `cdk` CLI. It also requires users to bootstrap their AWS environments the way CDK expects.
Also CDK is known for generating verbose CloudFormation identifiers. But we would like users to still be able to deploy superwerker via raw Cloudformation without a lot changes.

# The way forward

It's now possible to create CDK apps that don't require bootstrapping, or the CDK at deploy time. For that we can leverage the [CliCredentialsStackSynthesizer](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CliCredentialsStackSynthesizer.html).

1. Create an S3 asset bucket and make it public (https://github.com/superwerker/superwerker/pull/330).
1. Port superwerker templates to CDK (make sure to [override](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.CfnResource.html#overridewbrlogicalwbridnewlogicalid) the CFN identifiers with the ones from the templates to keep the upgrade path smooth).
1. Configure `CliCredentialsStackSynthesizer` for each stack. We only need the bucket and possibly the prefix.

    ```typescript
    new ExampleStack(app, 'ExampleStack', {
      env: devEnv,
      synthesizer: new CliCredentialsStackSynthesizer(
        {
          fileAssetsBucketName: ASSET_BUCKET_NAME,
          bucketPrefix: 'example',
        },
      ),
    });
    ```

1. Run `cdk synth` to generate all templates.
1. Run `cdk-assets publish -p idk.out/ExampleStack.assets.json` to upload the assets to the asset bucket.
1. Release templates in the normal way by uploading to S3.
1. Deploy templates normally via `aws cloudformation deploy`, AWS console or whatever.
1. Rejoice 🎺 🥁 :tada:.

**Comment by mavogel** [comment]
Remaining PRs to fully migrate to cdk

- #341 
- #348 
- #349 
- #350
- #351 
- #352 
- #353
