### ISSUE TITLE
bug: include tests for python funcs in test workflow

### ISSUE THREAD

**Issue by mavogel** [superwerker/superwerker#363]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behaviour

- the unit tests `cd cdk && yarn test` should also run the tests for the python functions
- there should be a separate command running those tests

### Actual Behaviour

we have to run these test separately and manually

### Important Factoids

- shouldn't we also migrate all python to ts functions as partially done in #379 ?
- or should be do a clean up as also suggested in #353 ?

### References

- #353

**Comment by skomp** [comment]
Regarding the migration to ts, I would vote yes. Unfortunately, we rely on the `awsapilib` in some cases, which is only available in python.
