### ISSUE TITLE
bug: CT with UPDATE_FROM_LATEST_RELEASE=true fails

### ISSUE THREAD

**Issue by mavogel** [superwerker/superwerker#387]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### superwerker Version

`v0.15.0`

### Expected Behaviour

`UPDATE_FROM_LATEST_RELEASE: true` tests also succeed

### Actual Behaviour

In the PR #379 we migrated CT to cdk, and did not test the `UPDATE_FROM_LATEST_RELEASE: true`. After merging to main the nightly build with all 4 combinations started and failed.

### Important Factoids

We'd also 
- test the `UPDATE_FROM_LATEST_RELEASE: true` in a PR
- idea would be to pass the `UPDATE_FROM_LATEST_RELEASE` env to the build. See #388 

### References

- #379

**Comment by skomp** [comment]
This manual test run https://github.com/superwerker/superwerker/actions/runs/4501510597/jobs/7922043651 on the latest head (before squashing) shows the update to be working
