### ISSUE TITLE
Enforce CloudFormation/IaC in Prod

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#39]
As a best practise
CloudFormation/IaC should be enforced in prod (and stage?) Accounts

Probably depends on sane pipelines: #38

**Comment by yawn** [comment]
Or via the family of [via global condition](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-calledvia) keys, depending on the principal usage of CloudFormation. This would not require pipelines per se.
