### ISSUE TITLE
Control Tower Setup needs retry logic

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#40]
Control Tower Setup often fails with transient errors, which can be fixed by simply retrying.

**Comment by yawn** [comment]
Does not occur anymore in the current MAVM setup, closing.

**Comment by s0enke** [comment]
Control Tower still fails occasionally during setup, e.g. https://github.com/superwerker/superwerker/issues/252 https://github.com/superwerker/superwerker/issues/177 https://github.com/superwerker/superwerker/issues/144

**Comment by s0enke** [comment]
Has not happened for a long time. In the meantime, we switched to awsapilib which handles retries as well. Also, it looks like the Control Tower landing zone setup itself seems to have stabilized.
