### ISSUE TITLE
Backup Stack: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

### ISSUE THREAD

**Issue by CptMo** [superwerker/superwerker#402]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behaviour

The backup stack should run through with activated trusted Activate trusted access with AWS Organizations. 

### Actual Behaviour

At the moment the installing the backup stack is broken due to the following error message:

> Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

The error is coming from [awsapilib](https://github.com/schubergphilis/awsapilib) being used in https://github.com/superwerker/superwerker/blob/main/templates/backup.yaml#L505

`[DEBUG]	2023-07-21T11:21:05.264Z	1e2e9abc-bb04-418c-b8fd-c86193146098	Getting url :None with arguments : {'url': None, 'headers': {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.5', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0', 'Cookie': 'aws-account-data=%7B%22marketplaceGroup%22%3A%22AWS%22%7D; ......
`
I was able to hunt it down to the line https://github.com/schubergphilis/awsapilib/blob/main/awsapilib/authentication/authentication.py#L501 where the URL could not be taken from the oauth headers. 

### Important Factoids

Fresh AWS Account without anything modified.

### Workaround

Current workaround is:

- Activate trusted access with AWS Organizations manually (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-activate-trusted-access.html)
- Adapted the lambda function (superwerker-Backup-XXXX-EnableCloudFormationStac-XXXX) which is automating this and added an anti-pattern to send success in case the "Invalid URL" error happens e.g. 
```
def exception_handling(function):
    def catch(event, context):
        try:
            function(event, context)
        except Exception as e:
            print(e)
            print(event)
            if 'Invalid URL' in str(e):
                cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
            else:
                cfnresponse.send(event, context, cfnresponse.FAILED, {})
```

### References

- [awsaplib](https://github.com/schubergphilis/awsapilib/issues/53)

**Comment by Shamshiel** [comment]
Hey, I'm running in the same issue now. 

Can you go in a little bit more detail on how you worked around this issue? Because retrying the failed "superwerker-Backup" stack results in a `Expected params.RoleARN to be a string` in my environment.

**Comment by CptMo** [comment]
@Shamshiel : Please use the "Update" functionality on the general superwerker CloudFormation Stack and NOT retry. If you use retry it will result in the described error. 

Also check the "workaround" section in the issue in order that the backup stack is running through

**Comment by Shamshiel** [comment]
@CptMo, thanks that was the issue, that I tried it with "Retry" and not the "Update" way. I already applied your workaround steps but I thought after that I just had to do a "Retry". 

Now it ran through this step but I'm stuck at a new "step" in the Backup-Stack. It fails on "BackupTagsEnforcement". Do you know if that could be of three accounts that are not enrolled in my Organizational Unit in the Control Tower? 

```
Resource handler returned message: "Failed to Create/Update OrganizationConformancePack superwerker-backup-enforce. Summary: [InternalError in 3 account(s), ]" 
```

**Comment by c-a-m-a-c** [comment]
Hi all, non-dev here, chiming in on the issue: we are able to see and reproduce the issue with multiple newly created AWS Accounts. The nested AWS CloudFormation stack superwerker-Backup-xyz fails to deploy ("CREATE_FAILED") because of a failed resource creation with logical ID "EnableCloudFormationStacksetsOrgAccessCustomResource".
After having researched the problem area (Amazon CloudWatch logs, AWS Lambda function) I understand there [is a call](https://github.com/superwerker/superwerker/blob/da58d43b0da8df4e846ac51a95806d2124fb4529/templates/backup.yaml#L505C2-L505C2) to enable [trusted access with AWS Organizations](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-activate-trusted-access.html). This obviously fails, you're also describing the workaround to enable access manually via console. Or "activate", I should say. Reading the documentation it occurred to me that this changed - while it used to be "enable" it's now "activate". The CLI command is also `aws cloudformation activate-organizations-access`. Could this be the issue here? Can anyone check/test and comment?

**Comment by CptMo** [comment]
Hey, @c-a-m-a-c, thanks for your question. To be honest, I did not understand your question completely. You also referenced the documentation, where in the screenshot, you can see what it looks like: 

https://docs.aws.amazon.com/images/AWSCloudFormation/latest/UserGuide/images/console-stacksets-enable-trusted-access-from-stacksets-list-new.png

You need to activate this button in the management account! I hope that helped. If not, please rephrase your question. Thanks.

**Comment by c-a-m-a-c** [comment]
Thank you for your quick reply. Sorry, I initially thought that the issue might be based on the fact that AWS changed wording from "enable organzation access" to "activate organization access". But it seems that's just related to wording in the documentation and actual calls never changed (wasn't able to find anything related to this).
Furthermore, I did not realize this issue actually is a note initiated by the contributors of superwerker.
So I'm sorry, nerver mind, we now know about the issue and our way around it. Keep up the great work!

**Comment by aperov9** [comment]
FYI: the fix is now on the main branch. the release pipeline is however broken due to some breaking changes on the GitHub action. you will need to wait a bit longer until the new release is published
