### ISSUE TITLE
latest tagged version (0.15.0) makes use of lambda runtime nodejs14.x, which is deprecated.

### ISSUE THREAD

**Issue by pgdad** [superwerker/superwerker#405]
### What

Update latest released/tagged version to not use lambda runtime nodejs14.x, as that version is deprecated.

### Why

Runtime no longer supported by AWS, making it impossible to provision a new superwerker setup.

**Comment by arkan9el** [comment]
I also add to this interesting point the End of Life of Python 3.7 since June 27, 2023.

It is recommended to update the version to python 3.11.
I do not know if this is a blocker for new provision.
