### ISSUE TITLE
Superwerker Template Fails on Control Tower Creation in AWS: Invalid AWS Regions Error

### ISSUE THREAD

**Issue by pragprogrammer** [superwerker/superwerker#417]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### superwerker Version
- v0.16.0 and v0.15.0

### Expected Behavior
- The Superwerker template should successfully deploy AWS Control Tower in the specified AWS region without encountering region-related errors, allowing for the smooth setup of a new AWS account infrastructure.

### Actual Behavior
- During the deployment of AWS Control Tower using the Superwerker template (versions v0.16.0 and v0.15.0), the process repeatedly fails with an error related to invalid AWS regions (specifically mentioning us-gov-west-1 and us-gov-east-1). This occurs despite the intended setup being in the us-west-2 region and not involving any GovCloud regions.

### Important Factoids
- This issue is occurring in a completely fresh AWS account, with no prior configurations or references to the GovCloud regions (us-gov-west-1 and us-gov-east-1). The error persists across different versions of the template and is encountered even when no specific region parameters are set by the user, indicating a potential issue with the template itself or its interaction with AWS services.

### References
- Related to issues with deploying AWS Control Tower in non-GovCloud regions using Superwerker templates.
- May involve discrepancies or recent changes in AWS API responses related to available Control Tower regions.
- Similar to problems faced by other users in deploying AWS infrastructure using templates in fresh accounts.

- #0000

**Comment by iainelder** [comment]
I cross-posted this as [awsapilib issue 58](https://github.com/schubergphilis/awsapilib/issues/58) because I think the solution depends on a change to that library.

**Comment by iainelder** [comment]
@costastf merged https://github.com/schubergphilis/awsapilib/pull/59 and released [version 3.1.4](https://github.com/schubergphilis/awsapilib/tree/3.1.4).

@aperov9, can you make a new version of superwerker that includes it?

@pragprogrammer, can you help us test this?

**Comment by aperov9** [comment]
@iainelder @pragprogrammer Created a new patch for superwerker with the new version as pre-release. Our end2end testing pipeline is broken, so need to verify manually if it actually fixes the problem: https://github.com/superwerker/superwerker/releases/tag/v0.16.1

**Comment by iainelder** [comment]
@aperov9 Thanks for publishing the new version. Are you able to do that manual verification?

If not, then @pragprogrammer , are you able to do it?

I would be able to do it later in the week, but not today. I would need to prepare a new standalone AWS account.

**Comment by aperov9** [comment]
@iainelder Yes, I will test the v0.16.1 tomorrow 👍🏻
