### ISSUE TITLE
RootMail nested stack stuck

### ISSUE THREAD

**Issue by yanneg** [superwerker/superwerker#480]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### superwerker Version

v1.0.0

### Expected Behaviour

The RootMail stack creation should continue.

### Actual Behaviour

The RootMail nested stack is stuck in `UPDATE_IN_PROGRESS`. It appears that the resource `RootMailReadyHandleWaitCondition` just hangs indefinitely with the `CREATE_IN_PROGRESS` status. From what I can tell, the RootMail looks like it should be ready. The `superwerker-RootMailReady` alarm is in the `OK` state and the RootMailReady Lambda has successful invocations so I'm confused as to how to proceed from here.

### Important Factoids

Things I've tried without success:

* Retrying the superwerker CFN stack after the eventual failure from timeout
* Manually sending a signal to the CFN resource, example: `aws cloudformation signal-resource --stack-name superwerker-RootMail-1HQRVH9AJSIC3 --logical-resource-id RootMailReadyHandleWaitCondition --unique-id $(uuidgen) --status SUCCESS --region us-west-2`

**Comment by peermuellerxw** [comment]
Hi @yanneg,

thanks for bug report. Did you configure your DNS correctly, as described in the [superwerker workshop](https://superwerker.awsworkshop.io/installation.html#dns-configuration)? You find the correct DNS name servers and see whether the configuration worked in the superwerker cloudwatch dashboard in your account.

**Comment by yanneg** [comment]
Yep, DNS is all wired correctly and the CW dashboard reports a successful DNS config too.

**Comment by peermuellerxw** [comment]
Can you check whether the RootMailReadyTrigger lambda function was triggered? It should have been triggered by the successful DNS configuration and signaled success to the root mail stack.

**Comment by yanneg** [comment]
Looks like it was triggered successfully.

<img width="551" alt="image" src="https://github.com/superwerker/superwerker/assets/48144/272493c4-b17d-4914-ba12-81984bd3f2ec">

The RootMailReady Lambda is also running successfully

<img width="550" alt="image" src="https://github.com/superwerker/superwerker/assets/48144/ca0a7fee-8dbb-4dc5-8cdd-5833c461318f">

**Comment by yanneg** [comment]
Nothing useful, unfortunately. I even tried sending the CFN signal manually via an `aws cloudformation signal-resource` invocation but that didn't have any effect either.

<img width="1532" alt="image" src="https://github.com/superwerker/superwerker/assets/48144/eec16fca-9fd1-4a76-b28f-04326bccbe67">

What's the best course of action given this state? Should I destroy the RootMail nested stack and then reapply the main superwerker stack?

**Comment by peermuellerxw** [comment]
I cannot recall that this ever happened to us.
You could either retry the deploy of the superwerker stack or try the [1.1.0](https://github.com/superwerker/superwerker/releases/tag/v1.1.0) pre-release version that we just released today. We have refactored the rootmail stack in the new release. Be aware though, that we are still doing our final manual tests for this release before we mark it as latest.

**Comment by yanneg** [comment]
The new release did the trick, thanks!
