### ISSUE TITLE
Implement account deletion / cattle accounts

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#57]
Implement this using the patterns from https://github.com/iann0036/aws-account-controller, potentially with a different solution for handling CCs.

This issue is being promoted to M1 now in order to get back our green pipelines.

**Comment by s0enke** [comment]
Unfortunately Account Deletion does not work, since it takes some time until accounts can be removed from the org. So we decided to build the OVM: https://github.com/superwerker/aws-organizations-vending-machine/issues
