### ISSUE TITLE
Versioning RFC

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#66]
In order to determine potentially breaking changes with alpha deployments I propose adding a versioning mechanism to our stacks, e.g. through stack [Metadata](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html). The versioning schema has not yet been defined through an ADR but could look like this for a pre-0.1: `0.0.1-47-20` for e.g. week 47, 2020.

Proposal would be for this to go into M1.

WDYT @s0enke

**Comment by s0enke** [comment]
Ok for me, maybe the git revision is even easier. Currently changes to master can happen several times during a day.

**Comment by yawn** [comment]
Probably difficult to do w/o touching the `superwerker.yml` automatically on every commit ... 🤷

**Comment by s0enke** [comment]
I think this could be rendered into the `superwerker.yaml` by the pipeline

**Comment by sbstjn** [comment]
https://www.conventionalcommits.org/
https://semver.org/

**Comment by yawn** [comment]
We have two versioning targets atm:

1.  internal project source version using "conventionalcommits" e.g. https://github.com/superwerker/superwerker/releases/tag/v0.4.0 - these versions need a release process towards S3
3. Quickstart releases
