### ISSUE TITLE
Security Hub + Delegate in Audit Account

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#7]
- [x] for new accounts
- [x] test for new account via account factory
- [x] integrity protection + tests
- [x] setup trigger control tower 
- [x] ~~how to handle the findings?~~ - descope this since (equivalent to GD) SH handles it's own findings / potentially those will be available via SSM/OC as well
- [x] ~~make SH findings "green" when possible (probably new ticket)~~ - descoped to #99
- [x] ADR

**Comment by yawn** [comment]
ADR ticked off by 921d59d6e240ac9c187c78f198766bb055a80575
