### ISSUE TITLE
Enable cost anomaly detection by default

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#77]
https://aws.amazon.com/aws-cost-management/aws-cost-anomaly-detection/

**Comment by yawn** [comment]
This is probably obsolete and/or at least competing with the currently implementation of our budget feature.

**Comment by s0enke** [comment]
How do both features compete?

**Comment by yawn** [comment]
We automatically adjust the forecast warning depending on usage - it _seems_ that this is almost the same thing, except that it can RCA/explain spikes: https://aws.amazon.com/blogs/aws-cost-management/preview-anomaly-detection-and-alerting-now-available-in-aws-cost-management

**Comment by bracki** [comment]
Will be fixed by #285

**Comment by s0enke** [comment]
Cost Anomaly detection and Auto-adjusting budgets are two different features.

**Comment by mavogel** [comment]
We'll keep it in mind anyway, for budget stack improvements
