### ISSUE TITLE
master → main

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#95]
- [x] Rename default GitHub branch to `main`
- [x] Update CloudFormation template for pipeline to use `main` branch
- [x] Update CloudFormation stack to use use `main` branch for CodePipeline runs/hooks

**Comment by sbstjn** [comment]
I enabled branch protection for `master`, so hopefully nobody can push to the outdated branch.

**Comment by s0enke** [comment]
> I enabled branch protection for master, so hopefully nobody can push to the outdated branch.
How about we delete the master branch entirely? Any reason to keep the branch? At least I would check it out by accident if it's still there because of muscle memory, so I'd rather like to get rid of it at all

**Comment by sbstjn** [comment]
I did not want to break any existing pull requests. (this comment is only available in Slack, sorry 🙈 )

**Comment by s0enke** [comment]
I think it would be OK to rebase the 4 open PRs in order to get rid of master entirely. What do you think?

**Comment by s0enke** [comment]
I changed the base of 2 remaining PRs and deleted the old master branch afterwards
